# Generated by Django 2.1 on 2018-10-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_categories_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_text',
            field=models.TextField(verbose_name='Добавить комментарий'),
        ),
    ]
