# Generated by Django 2.1 on 2018-09-19 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_usercreatenews_categories_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreatenews',
            name='author',
        ),
        migrations.RemoveField(
            model_name='usercreatenews',
            name='categories_news',
        ),
    ]
